/* NoDef, VariableTypeRequired */
def getWorkspace() {
    pwd().replace('%2F', '__')
}

node('') {
    ws(getWorkspace()) {

        final pipelineName = env.JOB_NAME.replace('%2F', '/')
        final buildNumber = env.BUILD_DISPLAY_NAME
        final branchName = env.BRANCH_NAME
        final buildUrl = env.BUILD_URL

        // remove the preceding 'MB-' of the pipeline name and remove the branch
        final fullServiceName = pipelineName.replaceAll("(?:MB-)?([\\w-]+)(?:(?:%2F|/)[\\w-\\.]+)*", "\$1")

        def LAST_STAGE_NAME = ''

        def deploymentConf = readJSON file: 'jenkins/deployment.json'
        def commandConf = readJSON file: 'jenkins/commands.json'

        // if branchname contains an url encoded slash, replace it with a slash
        pipelineName = pipelineName.replace('%2F', '/')

        def buildEnv = ''

        try {
            stage('Checkout') {
                LAST_STAGE_NAME = env.STAGE_NAME
                echo "Checking out ${branchName}..."
                checkout scm
                buildEnv = branchName.replace('master', 'prod').replace('develop', 'dev').replaceAll('release/.*', 'stage')
            }

//cmd:m2sedico:
            stage('Parse Commit and Commands'){
                commit = sh(returnStdout: true, script: 'git log -1 --oneline').trim()
                tmpCommit = commit.split("cmd:")

                cmdToRun = []

                for (cm in tmpCommit){
                    cmd = cm.split(":")
                    cmdToRun.push(cmd[0])
                }
            }

            echo 'Spawning docker container...'
            docker.image(deploymentConf.buildimage).inside {
                stage('PHP Build') {
                    LAST_STAGE_NAME = env.STAGE_NAME

                    def composer = fileExists 'composer.json'
                    if (composer){
                        echo 'Found composer.json.. running composer install'
                        sh 'composer install'
                    }
                }


                stage('JS Build') {
                    LAST_STAGE_NAME = env.STAGE_NAME

                    echo 'Running JS Build...'
                    def npm = fileExists 'package.json'
                    if (npm){
                        echo 'Found package.json.. running npm install'
                        sh 'npm install'
                    }
                }


                def hotfixes = fileExists 'hotfixes/'
                if (hotfixes) {
                    stage('Apply Hotfixes') {
                        LAST_STAGE_NAME = env.STAGE_NAME
                        sh 'cp -rf hotfixes/* ./'
                    }
                }


                stage('Create Artifact') {
                    LAST_STAGE_NAME = env.STAGE_NAME
                    def release = fileExists 'release.tar.gz'
                    if (release) {
                        sh 'rm release.tar.gz'
                    }

                    sh 'tar -zcvf release.tar.gz ./*'
                }
            }

            stage('Prepare Config'){
              echo "Decrypt Vault"
                withCredentials(bindings: [string(credentialsId: "vaultpassword", variable: 'password')]) {
                    sh '7z x -y -p${password} jenkins/configs/vault.7z jenkins/configs/vault/'
                }
            }

            stage('Deployment') {
                LAST_STAGE_NAME = env.STAGE_NAME

                println deploymentConf['environments']
                println deploymentConf['environments'][buildEnv]

                def serverWorkDir = "/tmp/jenkinsrelease-${fullServiceName}/"

                def destinations = deploymentConf['environments'][buildEnv]['destinations']

                echo "Copy artifact to defined destinations and untar it to ${serverWorkDir}"

                for (destination in destinations) {
                    def sshUserHost = destination['user'] + "@" + destination['host']
                    def config = destination['config']
                    sh "ssh ${sshUserHost} ' mkdir -p ${serverWorkDir}release/'"
                    sh "scp  release.tar.gz  ${sshUserHost}:${serverWorkDir}."
                    sh "ssh  ${sshUserHost} 'tar -xzvf ${serverWorkDir}release.tar.gz -C ${serverWorkDir}release/'"

                    echo "Apply config"
                    ssh "scp  jenkins/configs/vault/${config}  ${sshUserHost}:${serverWorkDir}."

                }




                echo "Copy release from ${serverWorkDir} to the real destination and run the defined commands"

                for (destination in destinations) {
                    def path = destination['path']
                    def sshUserHost = destination['user'] + "@" + destination['host']

                    sh "ssh  ${sshUserHost} 'sudo chmod 776 ${path}*  &&  sudo cp -r ${serverWorkDir}release/* ${path} && sudo chown www-data:www-data ${path}* -R'" //TODO!!!!




//cmd:m2sedico:
                    for (cmd in cmdToRun) {
                    //commandConf[cmd]['groups'].containsValue(destination['group']) geht nicht deswegen forschleife -.-
                        if(commandConf[cmd] ){

                            for(group in commandConf[cmd]['groups'] ){
                                if(group == destination['group']){
                                    sh "ssh  ${sshUserHost} 'cd ${path} &&  ${commandConf[cmd]['command']} '"
                                }
                            }
                        }
                    }
                    //TODO!!!
                    sh "ssh  ${sshUserHost} 'sudo chmod 776 ${path}*  && sudo chown www-data:www-data ${path}* -R'"
                }
            }

        } catch (e) {
            echo "Throwing Exception \"${e}\" --- Pipeline was not successful!"
            // slackSend(channel: slackRecipient, color: '#FF0000', message: "*Pipeline-Name:* ${pipelineName} \n*Build-Nummer:* ${buildNumber} \n"
            //         + "*Branch-Name:* ${branchName}\n:jenkins-failed: Pipeline failed in Step \"${LAST_STAGE_NAME}\"! (<${buildUrl}|Open>)")
            currentBuild.result = 'FAILED'      // Set result of currentBuild !Important!
            // Since we're catching the exception in order to report on it, we need to re-throw it, to ensure that the build is marked as failed
            throw e
        } finally {
            if (currentBuild.result == 'SUCCESS') {
            //    slackSend(channel: slackRecipient, color: 'good', message: "*Pipeline-Name:* ${pipelineName} \n*Build-Nummer:* ${buildNumber} \n"
            //            + "*Branch-Name:* ${branchName}\n:white_check_mark: Pipeline finished (<${buildUrl}|Open>)")
            }
        }
    }
}
